name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
    branches: dev
  # run it during pull request
#   pull_request:

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
  build:
    steps:
    - uses: actions/checkout@v3
      with:
        context: "./base-image/java/openjdk/11/Dockerfile"
    - name: Build the Docker image
      run: docker build . --file ./base-image/java/openjdk/11/Dockerfile --tag my-image-name:$(date +%s)
