name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: "us-west-2"
  AWS_ACCOUNT_ID: "999999999999"

jobs:

  build:
    name: Push to ECR
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v1

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1
    
    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@master
    #   with:
    #     role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-${{ github.event.repository.name }}
    #     aws-region: ${{ env.AWS_REGION }}
    
    # - name: Login to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v1
    # - name: Extract metadata (tags, labels) for Docker
    #   id: meta
    #   uses: docker/metadata-action@v3
    #   with:
    #     images: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ github.event.repository.name }}
    #     tags: |
    #       type=schedule,pattern=latest
    #       type=semver,pattern={{version}}
    #       type=semver,pattern={{major}}.{{minor}}
    #       type=semver,pattern={{major}}
    #       type=ref,event=branch

    - name: Build the Docker image
      with:
        context: "./base-image/java/openjdk/11/Dockerfile"
      # run: docker build . --file ./base-image/java/openjdk/11/Dockerfile --tag my-image-name:$(date +%s)
        push: false
        platforms: linux/amd64,linux/arm64
        # tags: ${{ steps.meta.outputs.tags }}
        tags: sample
        labels: image

          
